ansys/pyprimemesh

.github/workflows/ci_cd.yml, doc/Makefile, doc/make.bat
=> Workflow using pyansys actions

doc/source/conf.py
This PR needs to be merged ASAP to get the multi-version docs right... I'll do that with no approval and fix upcoming errors if needed. Problem is that while this is ongoing, documentation site is down. So we need to be fast.
=> Implementing multi-version docs

doc/source/index.rst
=> Fix link to pyansys on docs main page

.github/workflows/ci_cd.yml, doc/source/conf.py, pyproject.toml
Solves issues:
* Releases to public PyPI, not PyAnsys private PyPI
* Bumps dev version
=> Release to public PyPI - not private PyPI

pyproject.toml
Bump sphinx and ansys-sphinx themes manually
=> CHORE: Manually bump sphinx

.github/workflows/ci_cd.yml
I would like to add an action to check the branch name of the PR that is implemented in the PyAnsys actions, let me know what do you think about this
=> CI: Add branch name checking

.github/workflows/ci_cd.yml
Hot fix for issue caused in CI by #436
=> Run branch name check only on pull requests

src/ansys/meshing/prime/examples/__init__.py
Reverts pyansys/pyprimemesh#444
=> Revert "Update __init__.py"

src/ansys/meshing/prime/graphics/graphics.py
Let's not use `_vtk` because it's subject to change. Instead, let's use import `vtk` if we're using anything from `vtk`.
=> Don't use private module from pyvista

.github/workflows/ci_cd.yml, .github/workflows/label.yml, CONTRIBUTING.md, README.md, doc/source/conf.py, doc/source/contributing/index.rst, doc/source/getting_started/index.rst, pyproject.toml, src/ansys/meshing/prime/examples/download_utilities.py, src/ansys/meshing/prime/internals/utils.py
Renames `pyansys` to `ansys` due to organization renaming in Github
=> MAINT: GH organization rename

.github/workflows/ci_cd.yml, CONTRIBUTING.md, README.md, doc/source/_templates/sidebar-nav-bs.html, doc/source/conf.py, doc/source/contributing/index.rst, doc/source/getting_started/index.rst, requirements/requirements_docs.txt, setup.py, src/ansys/meshing/prime/_version.py, src/ansys/meshing/prime/examples/download.py, src/ansys/meshing/prime/graphics/graphics.py, src/ansys/meshing/prime/internals/launcher.py, src/ansys/meshing/prime/internals/utils.py
Adapts 0.2 documentation to new organization name. Also uses new sphinx version.
=> fix: Retrofit 0.2 doc version

src/ansys/meshing/prime/internals/defaults.py
Suggestion 1 in issue https://github.com/ansys/pyprimemesh/issues/484
=> Standardizing Windows user data path

README.md
=> MAINT: Add status badges to ReadMe

examples/gallery/01_bracket_scaffold.py, examples/gallery/02_lucid_mixing_elbow.py, examples/gallery/03_lucid_pipe_tee.py, examples/gallery/04_lucid_toy_car.py, examples/gallery/05_pcb_stacker.py, examples/gallery/06_blade_morph.py, examples/gallery/07_saddle_bracket.py, examples/gallery/08_lucid_generic_f1_rear_wing.py, examples/gallery/09_multi_layer_quad_mesh_pcb.py
There were a few typos and formatting errors in the newest example. While editing it, I also did a quick review of the older examples--because there is always something that can be better!
=> Review new example (and skim old examples)

.github/workflows/dependabot_automerge.yml
Adds a workflow that automatically merges dependabot PRs
=> feat: Dependabot automerge workflow

src/ansys/meshing/prime/__init__.py
=> Add missing TopoData entry to module

src/ansys/meshing/prime/autogen/commonstructs.py, src/ansys/meshing/prime/internals/utils.py, src/ansys/meshing/prime/lucid/mesh_util.py
MAINT: Update code from ADO - 0.6.0.dev6
=> MAINT: Update code from ADO - 0.6.0.dev6

.github/workflows/ci_cd.yml, pyproject.toml
=> updated dev version

.github/workflows/ci_cd.yml, doc/changelog.d/751.changed.md, pyproject.toml, src/ansys/meshing/prime/autogen/fileio.py, src/ansys/meshing/prime/autogen/fileiostructs.py, src/ansys/meshing/prime/autogen/primeconfig.py, src/ansys/meshing/prime/autogen/surfaceutilities.py, src/ansys/meshing/prime/autogen/surfaceutilitystructs.py, src/ansys/meshing/prime/autogen/thinvolumecontrol.py, src/ansys/meshing/prime/internals/error_handling.py
MAINT: Update code from ADO - 0.6.0.dev7
=> MAINT: Update code from ADO - 0.6.0.dev7

doc/changelog.d/757.added.md, src/ansys/meshing/prime/internals/defaults.py
=> Add PYPRIMEMESH_CONTAINER_USER_DATA environment variable

.github/workflows/ci_cd.yml, doc/changelog.d/759.changed.md, pyproject.toml, src/ansys/meshing/prime/autogen/connect.py, src/ansys/meshing/prime/autogen/connectstructs.py, src/ansys/meshing/prime/autogen/primeconfig.py, src/ansys/meshing/prime/core/mapdlcdbexportutils.py, src/ansys/meshing/prime/internals/error_handling.py, tests/lucid/test_mesh_utils.py
MAINT: Update code from ADO - 0.6.0.dev8
=> MAINT: Update code from ADO - 0.6.0.dev8

.github/workflows/ci_cd.yml, doc/changelog.d/775.changed.md, pyproject.toml
=> updated version for dev9

doc/changelog.d/781.miscellaneous.md, doc/source/user_guide/multizone.rst
=> updated multizone.rst

doc/changelog.d/785.changed.md, src/ansys/meshing/prime/graphics/graphics.py
=> maint: Update deprecated PyVista import

CONTRIBUTING.md, README.md, doc/changelog.d/783.miscellaneous.md
=> doc: Add local test and doc to CONTRIBUTING guide

.github/workflows/ci_cd.yml, doc/changelog.d/818.miscellaneous.md, doc/changelog.d/820.changed.md
=> added deploy_changelog job

doc/changelog.d/824.changed.md, pyproject.toml
=> maint: upgrade version to 0.6.1

doc/changelog.d/858.fixed.md, src/ansys/meshing/prime/core/model.py
=> fix: Main package import error

.github/workflows/ci_cd.yml, doc/changelog.d/898.maintenance.md
See https://github.com/ansys/actions/pull/576
=> maint: Remove branch action in favor of rulesets

doc/changelog.d/921.maintenance.md, pyproject.toml
updated ansys-api-meshing-prime version
=> updated ansys-api-meshing-prime version

doc/changelog.d/1052.fixed.md, doc/source/conf.py
=> fix: Revert napoleon extension

doc/changelog.d/1075.miscellaneous.md, src/ansys/meshing/prime/graphics/plotter.py
=> fix: Wrong param in PrimePlotter

doc/changelog.d/1081.miscellaneous.md, src/ansys/meshing/prime/internals/utils.py
=> updated the utils.py to sync ado side PRIME_GRAPHICS_PORT handling

doc/changelog.d/1089.miscellaneous.md, pyproject.toml
=> updated the version before tagging

.github/workflows/ci_cd.yml, doc/changelog.d/1100.miscellaneous.md
=> fix: Release action migration

doc/changelog.d/1110.miscellaneous.md, pyproject.toml
=> removed the dev4 version from pyproj.toml

.github/workflows/ci_cd.yml, doc/changelog.d/1141.miscellaneous.md
=> maint: Use merge queue

.github/workflows/ci_cd.yml, doc/changelog.d/1153.miscellaneous.md, pyproject.toml
=> stable release for 2025 R2 SP02

doc/changelog.d/1158.miscellaneous.md, pyproject.toml
=> updates the pyproj.toml

doc/changelog.d/1160.miscellaneous.md, doc/source/conf.py, doc/source/getting_started/index.rst
=> fix for search bar issue
